In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
import os
import glob

# Удалить все csv файлы из директории

In [2]:
# Укажите путь к директории
directory = '/Users/polinaivockina/Diploma_2025/dataset_fin'

# Использование glob для поиска всех CSV файлов
csv_files = glob.glob(os.path.join(directory, '*.csv'))

# Удаление каждого файла
for csv_file in csv_files:
    os.remove(csv_file)
    print(f'Удален файл: {csv_file}')

Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_49.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_48.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_15.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_29.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_1.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_28.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_14.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_16.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_2.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_3.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_17.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_13.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_7.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_6.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_12.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_38.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_10.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_4.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_5.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_11.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_39.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_34.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_20.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_8.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_9.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_21.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_35.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_23.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_37.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_36.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_22.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_26.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_32.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_33.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_27.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_19.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_31.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_25.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_24.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_30.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_18.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_43.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_42.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_56.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_40.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_54.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_55.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_41.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_45.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_51.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_50.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_44.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_52.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_46.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_47.csv
Удален файл: /Users/polinaivockina/Diploma_2025/dataset_fin/daily_solar_data_53.csv

# Создаем список ссылок на файлы .txt

In [3]:
# URL сайта, где находятся файлы
url = 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/'  # Замените на ваш URL

# Получаем HTML-контент страницы
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Находим все ссылки на файлы .txt
links = []
for a in soup.find_all('a', href=True):
    if a['href'].endswith('.txt'):
        links.append(a['href'])

# Если ссылки относительные, сделаем их абсолютными
base_url = url.rsplit('/', 1)[0]  # Получаем базовый URL
full_links = [link if link.startswith('http') else f"{base_url}/{link}" for link in links]
full_links.reverse()

In [4]:
full_links

['https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2025Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2025Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q3_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q2_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q1_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2017_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2017Q4_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2016_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2015_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2014_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2013_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2012_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2011_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2010_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2009_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2008_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2007_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2006_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2005_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2004_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2003_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2002_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2001_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2000_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1999_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1998_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1997_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1996_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1995_DSD.txt',
 'https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1994_DSD.txt']

# Сохраняем файлы .txt в csv

In [5]:
# Список для хранения данных
dataframes = []
k = 0
# Загружаем каждый файл и добавляем его в список DataFrame
for link in full_links:
    k = k+1
    try:
        print('Итерация:', k, '\nСсылка:', link) 
        print()
        # Скачиваем файл
        response = requests.get(link)
        data = response.text

        # Используем StringIO для обработки строк как файла
        data_io = StringIO(data)
        lines = data_io.readlines()
        
        # Ищем индекс строки, где начинаются данные (первая строка с данными)
        start_index = None
        for i, line in enumerate(lines):
            if line.startswith("2") or line.startswith("1") or line.startswith("0") or line.startswith("3"):
                start_index = i
                break
        
        # Если нашли индекс, создаем DataFrame
        if start_index is not None:
            # Читаем данные в DataFrame, пропуская строки до start_index
            df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True) 
            
            # Сохраняем DataFrame в CSV
            df.to_csv(f'daily_solar_data_{k}.csv', index=False) 
        
            print(f"Данные успешно сохранены в daily_solar_data_{k}.csv!\n")
        else:
            print("Данные не найдены.")
    except Exception as e:
        print(f"Ошибка при обработке {link}: {e}")

Итерация: 1
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2025Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_1.csv!

Итерация: 2
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2025Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_2.csv!

Итерация: 3
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_3.csv!

Итерация: 4
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_4.csv!

Итерация: 5
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_5.csv!

Итерация: 6
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2024Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_6.csv!

Итерация: 7
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_7.csv!

Итерация: 8
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_8.csv!

Итерация: 9
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_9.csv!

Итерация: 10
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2023Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_10.csv!

Итерация: 11
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_11.csv!

Итерация: 12
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_12.csv!

Итерация: 13
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_13.csv!

Итерация: 14
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2022Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_14.csv!

Итерация: 15
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_15.csv!

Итерация: 16
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_16.csv!

Итерация: 17
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_17.csv!

Итерация: 18
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2021Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_18.csv!

Итерация: 19
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_19.csv!

Итерация: 20
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_20.csv!

Итерация: 21
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_21.csv!

Итерация: 22
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2020Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_22.csv!

Итерация: 23
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_23.csv!

Итерация: 24
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_24.csv!

Итерация: 25
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_25.csv!

Итерация: 26
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2019Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_26.csv!

Итерация: 27
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_27.csv!

Итерация: 28
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_28.csv!

Итерация: 29
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q3_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_29.csv!

Итерация: 30
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q2_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_30.csv!

Итерация: 31
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2018Q1_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_31.csv!

Итерация: 32
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2017_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_32.csv!

Итерация: 33
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2017Q4_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_33.csv!

Итерация: 34
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2016_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_34.csv!

Итерация: 35
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2015_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_35.csv!

Итерация: 36
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2014_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_36.csv!

Итерация: 37
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2013_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_37.csv!

Итерация: 38
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2012_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_38.csv!

Итерация: 39
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2011_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_39.csv!

Итерация: 40
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2010_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_40.csv!

Итерация: 41
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2009_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_41.csv!

Итерация: 42
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2008_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_42.csv!

Итерация: 43
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2007_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_43.csv!

Итерация: 44
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2006_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_44.csv!

Итерация: 45
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2005_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_45.csv!

Итерация: 46
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2004_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_46.csv!

Итерация: 47
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2003_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_47.csv!

Итерация: 48
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2002_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_48.csv!

Итерация: 49
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2001_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_49.csv!

Итерация: 50
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/2000_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_50.csv!

Итерация: 51
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1999_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_51.csv!

Итерация: 52
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1998_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_52.csv!

Итерация: 53
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1997_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_53.csv!

Итерация: 54
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1996_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_54.csv!

Итерация: 55
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1995_DSD.txt

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

Данные успешно сохранены в daily_solar_data_55.csv!

Итерация: 56
Ссылка: https://www.ngdc.noaa.gov/stp/space-weather/swpc-products/annual_reports/daily_solar_indices_summaries/daily_solar_data/1994_DSD.txt

Данные успешно сохранены в daily_solar_data_56.csv!

/var/folders/j5/2z3wsnhn0w526_3mhsc123hr0000gn/T/ipykernel_91820/1089274686.py:28: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(StringIO(''.join(lines[start_index:])),delim_whitespace=True)

# Объединяем все датафреймы

In [6]:
import pandas as pd
column_list=["year","month","day","radio_flux","sunspot_number","sunspot_area","new_region","stanford_solar_mean_field","flares_x_ray_flux_bkgd","flares_x_ray_c","flares_x_ray_m","flares_x_ray_x","flares_optical_s","flares_optical_1","flares_optical_2","flares_optical_3"]

df_full = pd.DataFrame(columns=column_list)
df_full

Empty DataFrame
Columns: [year, month, day, radio_flux, sunspot_number, sunspot_area, new_region, stanford_solar_mean_field, flares_x_ray_flux_bkgd, flares_x_ray_c, flares_x_ray_m, flares_x_ray_x, flares_optical_s, flares_optical_1, flares_optical_2, flares_optical_3]
Index: []

In [7]:
column_list=["year","month","day","radio_flux","sunspot_number","sunspot_area","new_region","stanford_solar_mean_field","flares_x_ray_flux_bkgd","flares_x_ray_c","flares_x_ray_m","flares_x_ray_x","flares_optical_s","flares_optical_1","flares_optical_2","flares_optical_3"]
df_full = pd.read_csv(f'daily_solar_data_1.csv', sep=',', names=column_list)
df_full.head()

,year,month,day,radio_flux,sunspot_number,sunspot_area,new_region,stanford_solar_mean_field,flares_x_ray_flux_bkgd,flares_x_ray_c,flares_x_ray_m,flares_x_ray_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
0,2025,4,1,182,147,950,0,-999,*,12,2,0.1,10,0.2,0.3,0.4
1,2025,4,2,180,158,1030,1,-999,*,12,0,0.0,3,1.0,0.0,0.0
2,2025,4,3,178,124,930,0,-999,*,5,0,0.0,3,0.0,0.0,0.0
3,2025,4,4,180,163,1010,3,-999,*,5,0,0.0,3,0.0,0.0,0.0
4,2025,4,5,184,160,1010,2,-999,*,9,1,0.0,2,0.0,0.0,0.0

In [8]:
for i in range(2, 54):
    column_list=["year","month","day","radio_flux","sunspot_number","sunspot_area","new_region","stanford_solar_mean_field","flares_x_ray_flux_bkgd","flares_x_ray_c","flares_x_ray_m","flares_x_ray_x","flares_optical_s","flares_optical_1","flares_optical_2","flares_optical_3"]
    df = pd.read_csv(f'daily_solar_data_{i}.csv', sep=',', names=column_list)
    df_full = pd.concat([df_full, df])
    print(len(df_full))

150
242
334
425
516
608
700
791
881
973
1065
1156
1246
1338
1430
1521
1611
1703
1795
1886
1977
2069
2161
2252
2342
2707
2799
2891
2982
3072
3437
3529
3895
4260
4625
4990
5356
5721
6086
6451
6817
7182
7547
7912
8278
8643
9008
9373
9739
10104
10469
10834

# Обработка датасета

In [9]:
df2 = df_full.astype({'year':'int', 'month':'int', 'day':'int', 'radio_flux':'int', 'sunspot_number':'int', 'sunspot_area':'int', 'new_region':'int', 'stanford_solar_mean_field':'string', 'flares_x_ray_flux_bkgd':'string', 'flares_x_ray_c':'int', 'flares_x_ray_m':'int', 'flares_x_ray_x':'int', 'flares_optical_s':'int', 'flares_optical_1':'int', 'flares_optical_2':'int', 'flares_optical_3':'int'})
df_no_duplicates = df2.drop_duplicates()

In [10]:
print(len(df_no_duplicates))

10377

In [21]:
# проверка на удаление дублей
df_no_duplicates[df_no_duplicates.year == 2018].groupby('month')['day'].count()

month
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
Name: day, dtype: int64

In [16]:
df_no_duplicates[df_no_duplicates.year == 2018]

,year,month,day,radio_flux,sunspot_number,sunspot_area,new_region,stanford_solar_mean_field,flares_x_ray_flux_bkgd,flares_x_ray_c,flares_x_ray_m,flares_x_ray_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
0,2018,1,1,69,0,0,0,-999,A3.5,0,0,0,0,0,0,0
1,2018,1,2,70,0,0,0,-999,A3.2,0,0,0,0,0,0,0
2,2018,1,3,71,0,0,0,-999,A3.1,0,0,0,0,0,0,0
3,2018,1,4,70,13,20,1,-999,A3.1,0,0,0,0,0,0,0
4,2018,1,5,69,11,10,0,-999,A2.8,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2018,12,27,69,0,0,0,-999,A0.0,0,0,0,0,0,0,0
361,2018,12,28,69,0,0,0,-999,A1.0,0,0,0,0,0,0,0
362,2018,12,29,69,0,0,0,-999,A1.1,0,0,0,0,0,0,0
363,2018,12,30,69,0,0,0,-999,A1.1,0,0,0,0,0,0,0
364,2018,12,31,69,0,0,0,-999,A1.0,0,0,0,0,0,0,0

In [15]:
import pandas as pd
import seaborn as sns
from pandasql import sqldf

In [30]:
query = """
select 
     cast(case when length(cast(month as varchar)) = 1 and length(cast(day as varchar)) = 1  then CONCAT(cast(year as varchar), '-0', cast(month as varchar),  '-0',  cast(day as varchar))
               when length(cast(month as varchar)) = 1 and length(cast(day as varchar)) = 2  then CONCAT(cast(year as varchar), '-0', cast(month as varchar),  '-',  cast(day as varchar))
               when length(cast(month as varchar)) = 2 and length(cast(day as varchar)) = 1  then CONCAT(cast(year as varchar), '-', cast(month as varchar),  '-0',  cast(day as varchar))
               when length(cast(month as varchar)) = 2 and length(cast(day as varchar)) = 2  then CONCAT(cast(year as varchar), '-', cast(month as varchar),  '-',  cast(day as varchar))
      end as varchar) as calc_date
 , radio_flux
 , sunspot_number
 , sunspot_area
 , new_region
 , stanford_solar_mean_field
 , flares_x_ray_flux_bkgd
 , flares_x_ray_c
 , flares_x_ray_m
 , flares_x_ray_x
 , flares_optical_s
 , flares_optical_1
 , flares_optical_2
 , flares_optical_3                       
from df_no_duplicates
where length(cast(year as varchar)) = 4
;
"""
df_fin = sqldf(query)

In [38]:
df_fin.head()

,calc_date,radio_flux,sunspot_number,sunspot_area,new_region,stanford_solar_mean_field,flares_x_ray_flux_bkgd,flares_x_ray_c,flares_x_ray_m,flares_x_ray_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
0,2025-04-01,182,147,950,0,-999,*,12,2,0,10,0,0,0
1,2025-04-02,180,158,1030,1,-999,*,12,0,0,3,1,0,0
2,2025-04-03,178,124,930,0,-999,*,5,0,0,3,0,0,0
3,2025-04-04,180,163,1010,3,-999,*,5,0,0,3,0,0,0
4,2025-04-05,184,160,1010,2,-999,*,9,1,0,2,0,0,0

In [39]:
df_fin = df_fin.sort_values('calc_date')

In [40]:
df_fin

,calc_date,radio_flux,sunspot_number,sunspot_area,new_region,stanford_solar_mean_field,flares_x_ray_flux_bkgd,flares_x_ray_c,flares_x_ray_m,flares_x_ray_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
10012,1997-01-01,72,0,0,0,*,A0.5,0,0,0,-1,-1,-1,-1
10013,1997-01-02,72,0,0,0,*,A0.5,0,0,0,-1,-1,-1,-1
10014,1997-01-03,73,0,0,0,3,A0.5,0,0,0,-1,-1,-1,-1
10015,1997-01-04,74,13,10,1,*,A0.6,0,0,0,-1,-1,-1,-1
10016,1997-01-05,74,15,20,0,5,A0.7,0,0,0,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2025-05-26,133,113,790,1,-999,*,8,2,0,5,1,1,0
56,2025-05-27,137,116,790,2,-999,*,6,0,0,1,0,0,0
57,2025-05-28,144,126,880,1,-999,*,11,0,0,4,0,0,0
58,2025-05-29,145,122,870,0,-999,*,6,0,0,1,0,0,0
59,2025-05-30,157,107,980,1,-999,*,8,3,0,9,0,0,0

In [41]:
df_fin.set_index('calc_date', inplace=True)

In [42]:
df_fin

,radio_flux,sunspot_number,sunspot_area,new_region,stanford_solar_mean_field,flares_x_ray_flux_bkgd,flares_x_ray_c,flares_x_ray_m,flares_x_ray_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
calc_date,,,,,,,,,,,,,
1997-01-01,72,0,0,0,*,A0.5,0,0,0,-1,-1,-1,-1
1997-01-02,72,0,0,0,*,A0.5,0,0,0,-1,-1,-1,-1
1997-01-03,73,0,0,0,3,A0.5,0,0,0,-1,-1,-1,-1
1997-01-04,74,13,10,1,*,A0.6,0,0,0,-1,-1,-1,-1
1997-01-05,74,15,20,0,5,A0.7,0,0,0,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-26,133,113,790,1,-999,*,8,2,0,5,1,1,0
2025-05-27,137,116,790,2,-999,*,6,0,0,1,0,0,0
2025-05-28,144,126,880,1,-999,*,11,0,0,4,0,0,0
2025-05-29,145,122,870,0,-999,*,6,0,0,1,0,0,0
2025-05-30,157,107,980,1,-999,*,8,3,0,9,0,0,0

# Финальный датасет

In [45]:
df_fin.to_csv(f'daily_solar_data_fin.csv')